pull_request_rules:
  - name: request review on external contributor
    conditions:
      - -author=PurpleBooth
    actions:
      assign:
        add_users:
          - PurpleBooth

  - name: automatic rebase for dependencies
    conditions:
      - check-success=security-audit
      - check-success=check
      - check-success=test (ubuntu-latest)
      - check-success=bench (ubuntu-latest)
      - check-success=lints
      - base=main
      - author~=^dependabot(|-preview)\[bot\]$
    actions:
      queue:
        method: rebase
        rebase_fallback: merge
        name: default
