pull_request_rules:
  - name: automatic merge for Dependabot pull requests
    conditions:
      - author~=^dependabot(|-preview)\[bot\]$
      - check-success=security-audit
      - check-success=check
      - check-success=test (ubuntu-latest)
      - check-success=bench (ubuntu-latest)
      - check-success=lints
    actions:
      merge:
        strict: smart+fasttrack
        method: merge
  - name: automatic merge for releases
    conditions:
      - label=releases
      - check-success=security-audit
      - check-success=check
      - check-success=test (ubuntu-latest)
      - check-success=bench (ubuntu-latest)
      - check-success=lints
    actions:
      merge:
        strict: smart+fasttrack
        method: merge
