[package]
name = "mit-commit"
version = "1.16.0"
authors = [ "Billie Thompson <billie+mit-commit@billiecodes.com>" ]
edition = "2018"
license = "CC0-1.0"
description = "For building commit linters. This makes it eas."
categories = [ "parser-implementations", "parsing", "text-editors" ]
keywords = [ "git", "git-hooks" ]
readme = "README.md"
repository = "https://github.com/PurpleBooth/mit-commit"

[dependencies]
indoc = "1.0"
thiserror = "1.0.20"
regex = "1"
lazy_static = "1.4.0"

[dev-dependencies]
pretty_assertions = "0.6.1"
indoc = "1.0"
regex = "1"
criterion = "0.3"

[[bench]]
name = "commit_message"
harness = false
