[package]
name = "mit-commit"
version = "3.1.7"
authors = [ "Billie Thompson <billie+mit-commit@billiecodes.com>" ]
edition = "2018"
license = "CC0-1.0"
description = "For building commit linters. This makes it eas."
categories = [ "parser-implementations", "parsing", "text-editors" ]
keywords = [ "git", "git-hooks" ]
readme = "README.md"
repository = "https://github.com/PurpleBooth/mit-commit"

[dependencies]
indoc = "2.0.3"
thiserror = "1.0.48"
regex = "1.9.5"
lazy_static = "1.4.0"
miette = "5.10.0"
nom = "7.1.3"

[dev-dependencies]
tokio = { version = "1.32.0", features = ["full"] }
indoc = "2.0.3"
regex = "1.9.5"
criterion = "0.5.1"
quickcheck = "1.0.3"
quickcheck_macros = "1.0.0"
tempfile = "3.8.0"

[[bench]]
name = "commit_message"
harness = false
