[package]
name = "mit-commit"
version = "3.1.6"
authors = [ "Billie Thompson <billie+mit-commit@billiecodes.com>" ]
edition = "2018"
license = "CC0-1.0"
description = "For building commit linters. This makes it eas."
categories = [ "parser-implementations", "parsing", "text-editors" ]
keywords = [ "git", "git-hooks" ]
readme = "README.md"
repository = "https://github.com/PurpleBooth/mit-commit"

[dependencies]
indoc = "2.0.1"
thiserror = "1.0.39"
regex = "1.7.1"
lazy_static = "1.4.0"
miette = "5.5.0"
nom = "7.1.3"

[dev-dependencies]
tokio = { version = "1.26.0", features = ["full"] }
indoc = "2.0.1"
regex = "1.7.1"
criterion = "0.4.0"
quickcheck = "1.0.3"
quickcheck_macros = "1.0.0"
tempfile = "3.4.0"

[[bench]]
name = "commit_message"
harness = false
