[package]
name = "mit-commit"
version = "3.1.2"
authors = [ "Billie Thompson <billie+mit-commit@billiecodes.com>" ]
edition = "2018"
license = "CC0-1.0"
description = "For building commit linters. This makes it eas."
categories = [ "parser-implementations", "parsing", "text-editors" ]
keywords = [ "git", "git-hooks" ]
readme = "README.md"
repository = "https://github.com/PurpleBooth/mit-commit"

[dependencies]
indoc = "1.0.6"
thiserror = "1.0.31"
regex = "1.6.0"
lazy_static = "1.4.0"
miette = "5.1.0"
nom = "7.1.1"

[dev-dependencies]
tokio = { version = "1.19.2", features = ["full"] }
indoc = "1.0.6"
regex = "1.6.0"
criterion = "0.4.0"
quickcheck = "1.0.3"
quickcheck_macros = "1.0.0"
tempfile = "3.3.0"

[[bench]]
name = "commit_message"
harness = false
