[package]
name = "mit-commit"
version = "1.29.7"
authors = [ "Billie Thompson <billie+mit-commit@billiecodes.com>" ]
edition = "2018"
license = "CC0-1.0"
description = "For building commit linters. This makes it eas."
categories = [ "parser-implementations", "parsing", "text-editors" ]
keywords = [ "git", "git-hooks" ]
readme = "README.md"
repository = "https://github.com/PurpleBooth/mit-commit"

[dependencies]
indoc = "1.0.3"
thiserror = "1.0.23"
regex = "1.4.3"
lazy_static = "1.4.0"

[dev-dependencies]
pretty_assertions = "0.7.1"
indoc = "1.0.3"
regex = "1.4.3"
criterion = "0.3.3"

[[bench]]
name = "commit_message"
harness = false
