[package]
name = "mit-commit"
version = "3.0.1"
authors = [ "Billie Thompson <billie+mit-commit@billiecodes.com>" ]
edition = "2018"
license = "CC0-1.0"
description = "For building commit linters. This makes it eas."
categories = [ "parser-implementations", "parsing", "text-editors" ]
keywords = [ "git", "git-hooks" ]
readme = "README.md"
repository = "https://github.com/PurpleBooth/mit-commit"

[dependencies]
indoc = "1.0.3"
thiserror = "1.0.30"
regex = "1.5.4"
lazy_static = "1.4.0"
miette = "4.0.1"
nom = "7.1.0"

[dev-dependencies]
tokio = { version = "1.16.1", features = ["full"] }
indoc = "1.0.3"
regex = "1.5.4"
criterion = "0.3.5"
quickcheck = "1.0.3"
quickcheck_macros = "1.0.0"

[[bench]]
name = "commit_message"
harness = false
